version = 0.1

[default.deploy.parameters]
stack_name = "azubi-va"
resolve_s3 = true
s3_prefix = "azubi-va"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"azubi-va\""
image_repositories = []
